import { CSSProperties } from "react";

export const guardianForumPageStyles = {
  container: {
    backgroundColor: "#1d1551",
    padding: "20px",
    borderRadius: "8px",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    boxSizing: "border-box",
  } as CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    padding: "0 20px",
    flexWrap: "wrap",
  } as CSSProperties,
  createButton: {
    backgroundColor: "#ffc107",
    color: "#000",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    alignSelf: "flex-start",
  } as CSSProperties,
  body: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    padding: "20px",
  } as CSSProperties,
  label: {
    color: "#f4f4f4",
    fontSize: "1rem",
    marginBottom: "10px",
  } as CSSProperties,
  select: {
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    width: "100%",
    marginBottom: "20px",
  } as CSSProperties,
  topicsTitle: {
    color: "#f4f4f4",
    fontSize: "1.5rem",
    margin: "20px 0 10px 0",
  } as CSSProperties,
  topicsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
  } as CSSProperties,
  topic: {
    backgroundColor: "#333",
    borderRadius: "5px",
    padding: "15px",
  } as CSSProperties,
  topicTitle: {
    color: "#ffc107",
    fontSize: "1.2rem",
    cursor: "pointer",
    marginBottom: "5px",
  } as CSSProperties,
  topicDescription: {
    color: "#ccc",
    fontSize: "1rem",
  } as CSSProperties,
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "opacity 0.3s ease-in-out",
    opacity: 1,
  } as CSSProperties,
  modal: {
    backgroundColor: "#1d1551",
    padding: "20px",
    borderRadius: "8px",
    width: "95%",
    maxWidth: "700px",
    maxHeight: "700px",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    transition: "transform 0.3s ease-in-out",
    transform: "scale(1)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  } as CSSProperties,
  modalHeader: {
    width: "100%",
    borderBottom: "1px solid #ccc",
    paddingBottom: "10px",
    marginBottom: "20px",
    textAlign: "center",
  } as CSSProperties,
  modalBody: {
    width: "100%",
    height: "600px",
    textAlign: "center",
  } as CSSProperties,
  commentsContainer: {
    width: "100%",
    height: "calc(100% - 150px)",
    marginTop: "20px",
  } as CSSProperties,
  commentsScrollable: {
    maxHeight: "320px",
    overflowY: "auto",
  },
  comment: {
    backgroundColor: "#333",
    borderRadius: "5px",
    padding: "10px",
    marginBottom: "10px",
    textAlign: "left",
  } as CSSProperties,
  commentAuthor: {
    color: "#ffc107",
    fontWeight: "bold",
    marginBottom: "5px",
  } as CSSProperties,
  commentText: {
    color: "#ccc",
  } as CSSProperties,
  input: {
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    width: "100%",
    marginBottom: "10px",
  } as CSSProperties,
  textarea: {
    borderRadius: "5px",
    border: "1px solid #ccc",
    width: "100%",
    height: "100px",
    marginBottom: "10px",
    resize: "none",
  } as CSSProperties,
  modalActions: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "20px",
    gap: "10px",
  } as CSSProperties,
  submitButton: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginBottom: "5px",
  } as CSSProperties,
  deleteButton: {
    backgroundColor: "#f00",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginBottom: "5px",
    position: "absolute",
    bottom: "20px",
    right: "20px",
  } as CSSProperties,
  backButton: {
    backgroundColor: "#ffc107",
    color: "#000",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginBottom: "20px",
    alignSelf: "flex-start",
  } as CSSProperties,
  cancelButton: {
    backgroundColor: "#dc3545",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#c82333",
    },
  } as CSSProperties,
};
