export const adminPageStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    color: '#f4f4f4',
    backgroundColor: '#1d2a50',
    width: '100%',
    height: '100vh',
    position: 'relative',
    overflowY: 'auto',
  },
  header: {
    top: '0',
    backgroundColor: '#1d2a50',
    color: '#fff',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
    width: '100%',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerImage: {
    width: '150px',
    position: 'relative',
    zIndex: 2,
    padding: '1rem',
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    position: 'absolute',
    top: '0',
    right: '0',
    zIndex: 1,
  },
  userInfo: {
    zIndex: 2,
    marginLeft: '2rem',
  },
  welcomeText: {
    fontSize: '1.8rem',
    color: '#fff',
  },
  logoutButton: {
    backgroundColor: '#ff4747',
    fontSize: '1rem',
    color: '#fff',
    border: 'none',
    padding: '1rem 0.5rem',
    margin: '5rem',
    borderRadius: '520px',
    cursor: 'pointer',
    zIndex: 2,
  },
  body: {
    padding: '2rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
  },
  subBody: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1.5rem',
    flexWrap: 'wrap',
  },
  bodyButton: {
    backgroundColor: '#427390',
    fontSize: '1.2rem',
    color: '#fff',
    padding: '1.5rem 3rem',
    margin: '1rem',
    border: 'none',
    borderRadius: '20px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: '#315b73',
      transform: 'scale(1.05)',
    },
    '@media (maxWidth: 768px)': {
      padding: '1rem 2rem',
      fontSize: '1rem',
    },
  },
};
