export const adminPageStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    color: '#f4f4f4',
    backgroundColor: '#1d1551',
    overflow: 'hidden',
    width: '100%',
    height: '100vh',
    position: 'relative',
  },
  header: {
    top: '0',
    backgroundColor: '#1d1551',
    color: '#fff',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
    width: '100%',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1rem',
  },
  headerImage: {
    width: '180px',
    position: 'relative',
    zIndex: 2,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    position: 'absolute',
    top: '0',
    left: '0',
    zIndex: 1,
  },
  headerButton: {
    backgroundColor: '#4273ff',
    fontSize: '1.5rem',
    color: '#fff',
    border: 'none',
    padding: '1rem 2rem',
    marginRight: '2rem',
    borderRadius: '5px',
    cursor: 'pointer',
    zIndex: 2,
  },
  body: {
    padding: '10rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
  },
  subBody: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '3rem',
  },
  bodyButton: {
    backgroundColor: '#427390',
    fontSize: '1.5rem',
    color: 'fff',
    padding: '2rem 5rem',
    marginRight: '4rem',
    marginLeft: '4rem',
    border: 'none',
    borderRadius: '20px',
    cursor: 'pointer',
  },
};
