export const reportsPageStyles = {
  container: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    color: '#f4f4f4',
    backgroundColor: '#1d1551',
    width: '100%',
    height: '100vh',
  },
  header: {
    top: '0',
    backgroundColor: '#427390',
    color: '#fff',
    padding: '2.5rem 2rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
    paddingBottom: '3rem',
    marginBottom: '3rem',
  },
  tableContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
  },
  table: {
    width: '100%',
    maxWidth: '1500px',
    borderCollapse: 'collapse',
    marginBottom: '2rem',
    margin: '0 auto',
  },
  tableHead: {
    backgroundColor: '#4273ff',
  },
  tableBody: {
    textAlign: 'center',
  },
  tableRow: {
    height: '50px',
  },
  tableCell: {
    border: '1px solid #ccc',
    padding: '10px',
    color: '#fff',
  },
  select: {
    padding: '1rem',
    borderRadius: '5px',
    border: '1px solid #ccc',
    width: '100%',
    marginBottom: '2rem',
  },
  weekNavigation: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '2rem',
  },
  dateRange: {
    marginBottom: '2rem',
    fontSize: '1.2rem',
    color: '#fff',
    textAlign: 'center',
  },
  button: {
    padding: '0.5rem 1rem',
    borderRadius: '5px',
    border: 'none',
    backgroundColor: '#4273ff',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '1rem',
  },
  buttonHover: {
    backgroundColor: '#365bbf',
  },
};
