import { CSSProperties } from "react";

export const attendancePageStyles = {
  container: {
    backgroundColor: "#1d1551",
    padding: "20px",
    borderRadius: "8px",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    boxSizing: "border-box",
  } as CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
    width: "100%",
    padding: "0 20px",
    flexWrap: "wrap",
  } as CSSProperties,
  backButton: {
    backgroundColor: "#ffc107",
    color: "#000",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginBottom: "20px",
    alignSelf: "flex-start",
  } as CSSProperties,
  body: {
    display: 'flex',
    flexDirection: 'column',
    padding: '2rem',
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    width: "100%",
  } as CSSProperties,
  label: {
    color: "#f4f4f4",
    fontSize: "1rem",
  } as CSSProperties,
  select: {
    padding: '1rem',
    borderRadius: '5px',
    border: '1px solid #ccc',
    width: '100%',
    marginBottom: '2rem',
    fontSize: '1rem',
  },
  input: {
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    width: "100%",
  } as CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "15px",
  } as CSSProperties,
  tableHead: {
    backgroundColor: "#0056b3",
    color: "#fff",
    fontWeight: "bold",
    padding: "10px",
  } as CSSProperties,
  tableBody: {
    backgroundColor: "#333333",
    color: "#fff",
  } as CSSProperties,
  tableCell: {
    padding: "10px",
    borderBottom: "1px solid #555",
    textAlign: "center",
  } as CSSProperties,
  checkbox: {
    transform: "scale(1.5)",
  } as CSSProperties,
  submitButton: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    alignSelf: "center",
    marginTop: "20px",
  } as CSSProperties,
};
