import { CSSProperties } from "react";

export const attendancePageStyles = {
  container: {
    top: '0',
    flexDirection: 'column',
    justifyContent: 'center',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    color: '#f4f4f4',
    backgroundColor: '#1d1551',
    width: '100%',
    height: '100vh',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  header: {
    top: '0',
    backgroundColor: '#427390',
    color: '#fff',
    padding: '2.5rem 2rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
    borderRadius: '8px',
    marginBottom: '2rem',
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    padding: '2rem',
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    width: "100%",
  } as CSSProperties,
  label: {
    color: "#f4f4f4",
    fontSize: "1rem",
  } as CSSProperties,
  select: {
    padding: '1rem',
    borderRadius: '5px',
    border: '1px solid #ccc',
    width: '100%',
    marginBottom: '2rem',
    fontSize: '1rem',
  },
  input: {
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    width: "100%",
  } as CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "15px",
  } as CSSProperties,
  tableHead: {
    backgroundColor: "#0056b3",
    color: "#fff",
    fontWeight: "bold",
    padding: "10px",
  } as CSSProperties,
  tableBody: {
    backgroundColor: "#333333",
    color: "#fff",
  } as CSSProperties,
  tableCell: {
    padding: "10px",
    borderBottom: "1px solid #555",
    textAlign: "center",
  } as CSSProperties,
  checkbox: {
    transform: "scale(1.5)",
  } as CSSProperties,
  submitButton: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    alignSelf: "center",
    marginTop: "20px",
  } as CSSProperties,
};
