export const attendancePageStyles = {
  container: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    backgroundColor: '#1d1551',
    color: '#f4f4f4',
    width: '100%',
    minHeight: '100vh',
  },
  header: {
    top: '0',
    backgroundColor: '#427390',
    color: '#fff',
    padding: '2.5rem 2rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '2rem',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: '600px',
  },
  label: {
    color: '#fff',
    marginBottom: '0.5rem',
  },
  input: {
    marginBottom: '1rem',
    padding: '0.5rem',
    width: '100%',
    maxWidth: '400px',
    borderRadius: '4px',
    border: '1px solid #ddd',
  },
  select: {
    marginBottom: '1rem',
    padding: '0.5rem',
    width: '100%',
    maxWidth: '400px',
    borderRadius: '4px',
    border: '1px solid #ddd',
  },
  table: {
    width: '100%',
    maxWidth: '600px',
    borderCollapse: 'collapse',
    marginBottom: '2rem',
  },
  tableHead: {
    backgroundColor: '#2d2369',
    color: '#f4f4f4',
  },
  tableCell: {
    border: '1px solid #ddd',
    padding: '8px',
  },
  submitButton: {
    backgroundColor: '#28a745',
    color: '#fff',
    padding: '1rem',
    cursor: 'pointer',
    border: 'none',
    borderRadius: '4px',
  },
};
