import { CSSProperties } from "react";

export const subjectsPageStyles = {
  container: {
    top: '0',
    flexDirection: 'column',
    justifyContent: 'center',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    color: '#f4f4f4',
    backgroundColor: '#1d1551',
    width: '100%',
    height: '100vh',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  header: {
    top: '0',
    backgroundColor: '#427390',
    color: '#fff',
    padding: '2.5rem 2rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
    borderRadius: '8px',
    marginBottom: '2rem',
  },
  body: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  } as CSSProperties,
  backButton: {
    backgroundColor: "#ffc107",
    color: "#000",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginBottom: "20px",
    alignSelf: "flex-start",
  } as CSSProperties,
  filterContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginBottom: "20px",
    width: "100%",
  } as CSSProperties,
  filterInput: {
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    flex: "1 1 200px",
  } as CSSProperties,
  addButton: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
  } as CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse",
  } as CSSProperties,
  tableHead: {
    backgroundColor: "#0056b3",
    color: "#fff",
    fontWeight: "bold",
  } as CSSProperties,
  saveButton: {
    backgroundColor: '#4CAF50',
    color: 'white',
    padding: '10px 20px',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
    margin: "5px",
  },

  closeButton: {
    backgroundColor: '#f44336',
    color: 'white',
    padding: '10px 20px',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '16px',
    margin: "5px",
  },
  tableBody: {
    backgroundColor: "#333333",
    color: "#fff",
  } as CSSProperties,
  editButton: {
    backgroundColor: "#ffc107",
    color: "#fff",
    padding: "5px 10px",
    border: "none",
    borderRadius: "5px",
    marginRight: "5px",
  } as CSSProperties,
  deleteButton: {
    backgroundColor: "#dc3545",
    color: "#fff",
    padding: "5px 10px",
    border: "none",
    borderRadius: "5px",
  } as CSSProperties,
  modalOverlay: {
    position: "fixed" as "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } as CSSProperties,
  modal: {
    backgroundColor: "#fff",
    padding: "20px",
    borderRadius: "8px",
    minWidth: "400px",
  } as CSSProperties,
  input: {
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    width: "90%",
    marginBottom: "10px",
  } as CSSProperties,
  modalActions: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "20px",
  } as CSSProperties,
  updateButton: {
    backgroundColor: "#007BFF",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    margin: "5px",
  } as CSSProperties,
  cancelButton: {
    backgroundColor: "#6c757d",
    color: "#fff",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    margin: "5px",
  } as CSSProperties,
  modalContent: {
    backgroundColor: '#1d1551',
    padding: '2rem',
    borderRadius: '8px',
    width: '90%',
    maxWidth: '500px',
    color: '#f4f4f4',
  } as CSSProperties,
};
